### ISSUE TITLE
хватит бездельничать

### ISSUE THREAD

**Issue by nexussed** [PBModular/bot#2]
бездельничать плохо
найдите работу наконец 
![image](https://user-images.githubusercontent.com/70901289/218268576-8345f3ef-6d19-496c-8730-cdfa347841d6.png)

**Comment by SanyaPilot** [comment]
прошу прощения, я _experienced_ **_pythonist_**!
![изображение](https://user-images.githubusercontent.com/29630471/218269452-52da477a-5ba9-4728-b981-72981acc6155.png)

**Comment by nexussed** [comment]
нет, вы dalbaeb 
![image](https://user-images.githubusercontent.com/70901289/218269509-8e01b6c4-41e0-429f-9efc-36c77133044c.png)

**Comment by SanyaPilot** [comment]
Нет, вы!
![изображение](https://user-images.githubusercontent.com/29630471/218269876-59e00cbd-ca20-45a2-afec-75f697bcb205.png)

**Comment by Ultra119** [comment]
Может хватит бездельничать?
![image](https://github.com/PBModular/bot/assets/64977575/32d38537-caef-4c29-8b81-39bdb4ad8998)

**Comment by SanyaPilot** [comment]
Да не бездельничаю я, отстаньте ептить

**Comment by ZaNYAshlin** [comment]
> Да не бездельничаю я, отстаньте ептить
Прекратите бездельничать![grusha_polza_i_vred_oblogka_960-960x540.jpg](https://github.com/PBModular/bot/assets/74340112/36717058-4b7a-4475-ad52-1cb5dc9822dd)

**Comment by Ultra119** [comment]
Сколько можно бездельничать?
![img3 akspic ru-morozhenoe-frukty-yagoda-klubnika-ogurec-5184x3456](https://github.com/PBModular/bot/assets/64977575/7364c82f-8407-4588-aa00-9cd88e10841f)

**Comment by dushkinmir** [comment]
![IMG_20230729_144322_040](https://github.com/PBModular/bot/assets/126559713/38d03f6d-0e51-4bd8-9c99-5ff151c087b6)
саня гей

**Comment by SanyaPilot** [comment]
Дорогое комьюнити, спешу сообщить, что я не бездельничаю, а ем арбуз. Всем добра
![86b0744689c8107924eaa1e761c8f107.jpg](https://github.com/PBModular/bot/assets/29630471/ca24ae89-9285-4802-bf92-189cd8c5ab3d)

**Comment by dushkinmir** [comment]
ого

**Comment by nexussed** [comment]
срочно начинаем работать, хватит бездельничать ну уже на деле ![image](https://github.com/PBModular/bot/assets/70901289/a96606bd-de30-46aa-8e3d-824f29af4fea)
